import os
import re

# All dataset trees referenced below live under a single root directory.
# Resolution order:
#   1. ONECANVAS_DATA_ROOT env var (explicit override, always wins).
#   2. A `datasets/` directory sitting next to the repo root, derived from this
#      file's own location (no hardcoded absolute path). This is the common
#      checkout layout (`<parent>/onecanvas`, `<parent>/datasets`) and means
#      launches via run-on-job / submit-job / eval don't have to remember to
#      export the var. Guarded on the directory actually existing so a
#      collaborator with a different layout still gets the explicit error below
#      rather than silently loading the wrong filesystem tree.
_DATA_ROOT = os.environ.get("ONECANVAS_DATA_ROOT")
if not _DATA_ROOT:
    _repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
    _sibling_datasets = os.path.join(os.path.dirname(_repo_root), "datasets")
    if os.path.isdir(_sibling_datasets):
        _DATA_ROOT = _sibling_datasets
if not _DATA_ROOT:
    raise RuntimeError(
        "ONECANVAS_DATA_ROOT is not set. Export it to the directory that "
        "contains scannet/, scannetpp/, arkitscenes/, vlm_annotations/, etc., "
        "before launching anything that imports onecanvas.data.\n"
        "  example: export ONECANVAS_DATA_ROOT=/path/to/your/datasets"
    )


SCANQA = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/ScanQA/data/qa/ScanQA_v1.0_train.json",
    "data_path": f"{_DATA_ROOT}/scannet/scannet_preprocessed/",
}

SQA3D = {
    "question_path_train": f"{_DATA_ROOT}/vlm_annotations/sqa_task/balanced/v1_balanced_questions_train_scannetv2.json",
    "question_path_val": f"{_DATA_ROOT}/vlm_annotations/sqa_task/balanced/v1_balanced_questions_val_scannetv2.json",
    "question_path_test": f"{_DATA_ROOT}/vlm_annotations/sqa_task/balanced/v1_balanced_questions_test_scannetv2.json",
    "answer_path_train": f"{_DATA_ROOT}/vlm_annotations/sqa_task/balanced/v1_balanced_sqa_annotations_train_scannetv2.json",
    "answer_path_val": f"{_DATA_ROOT}/vlm_annotations/sqa_task/balanced/v1_balanced_sqa_annotations_val_scannetv2.json",
    "answer_path_test": f"{_DATA_ROOT}/vlm_annotations/sqa_task/balanced/v1_balanced_sqa_annotations_test_scannetv2.json",
    "data_path": f"{_DATA_ROOT}/scannet/scannet_preprocessed/",
}

# Same paths as SQA3D, but flagged so the data processor places the panorama at
# the situated agent's position and orients it along the agent's rotation. Lets
# a training mix contain both plain SQA3D (canvas-centered) and pose-conditioned
# SQA3D without needing a global flag.
SQA3D_AGENT_POSE = {
    **SQA3D,
    "force_agent_pose": True,
}

MV_SCANQA = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/MV-ScanQA/ScanQA_mv_train_filtered_cleaned.json",
    "data_path": f"{_DATA_ROOT}/scannet/scannet_preprocessed/",
}

# ---------------------------------------------------------------------------
# Multi-source datasets (ARKitScenes + ScanNet++ + ScanNet).
# data_path_map maps the "data_source" / "dataset" / video-prefix value that
# appears in each annotation item to the corresponding on-disk scene root.
# The loader resolves the actual scene directory shape at runtime.
# ---------------------------------------------------------------------------
_DATA_PATH_MAP = {
    "arkitscenes": f"{_DATA_ROOT}/arkitscenes/raw/",
    "scannetpp":   f"{_DATA_ROOT}/scannetpp/data/",
    "scannet":     f"{_DATA_ROOT}/scannet/scannet_preprocessed/",
}

VSI_BENCH = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vsi-bench/test.jsonl",
    "data_path_map": _DATA_PATH_MAP,
}

VLM3R_VSIBENCH = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/vsibench_train/",
    "data_path_map": _DATA_PATH_MAP,
}

# Matched tool-call track (agentic-onecanvas): the SAME vlm3r vsibench items
# (ScanNet subset), preamble baked into the question text, labels =
# distance()/direction() calls from ScanNet GT instances in the raw world
# frame, transformed per sample by the toolcall_points loader branch in
# data_processor_3d.py. Generated by
# agentic-onecanvas/scripts/build_toolcall_matched_annotations.py.
TOOLCALL_MATCHED = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_matched/toolcall_matched_train.json",
    "data_path_map": _DATA_PATH_MAP,
}
TOOLCALL_MATCHED_VAL = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_matched/toolcall_matched_val.json",
    "data_path_map": _DATA_PATH_MAP,
}
# Tool-call MARKER feedback loop (question_type == "toolcall_marker_points",
# handled by the toolcall_marker_points branch in data_processor_3d.py).
# Whole-episode teacher-forced place_marker/python sequences with inline marker
# PAIR tokens. Generated by
# agentic-onecanvas/scripts/build_toolcall_marker_annotations.py.
TOOLCALL_MARKER = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_marker/toolcall_marker_train.json",
    "data_path_map": _DATA_PATH_MAP,
}
TOOLCALL_MARKER_VAL = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_marker/toolcall_marker_val.json",
    "data_path_map": _DATA_PATH_MAP,
}

# DELTA correction grammar (2026-07-21). Same episodes and same generator, one
# difference: the correction turn is adjust_marker(marker_id, delta) instead of a
# second place_marker at ground truth. Separate files, never overwriting the
# absolute build, so the two are directly comparable as a supervision ablation.
# Built with --correction_grammar delta.
TOOLCALL_MARKER_DELTA = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_marker/toolcall_marker_delta_train.json",
    "data_path_map": _DATA_PATH_MAP,
}
TOOLCALL_MARKER_DELTA_VAL = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_marker/toolcall_marker_delta_val.json",
    "data_path_map": _DATA_PATH_MAP,
}

# s2corr / s2nocorr = the STAGE-2 A/B on whether corrections are needed at all
# (2026-08-01). Both are delta-grammar builds off the same source records with
# the same seed, and they differ in exactly one parameter: s2nocorr passes
# --standard_prob 1.0, so every marker is placed at exact GT and no correction
# is supervised anywhere, while s2corr keeps the historical 0.35 standard /
# 0.65 bad-placement mix. Train both from the same merged stage 1 for the same
# steps and the difference in answer accuracy IS the value of the correction
# branch. If they tie, the branch buys nothing and should be dropped rather
# than improved. Bands are the historical defaults rather than --noise_median
# derived, because the model that stage 2 starts from places NO markers at all
# on real scenes (zero-shot, 48/48 answered without the tool), so there is no
# own-error distribution to match yet.
TOOLCALL_MARKER_DELTA_S2CORR = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_marker/toolcall_marker_delta_s2corr_train.json",
    "data_path_map": _DATA_PATH_MAP,
}
TOOLCALL_MARKER_DELTA_S2CORR_VAL = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_marker/toolcall_marker_delta_s2corr_val.json",
    "data_path_map": _DATA_PATH_MAP,
}
TOOLCALL_MARKER_DELTA_S2NOCORR = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_marker/toolcall_marker_delta_s2nocorr_train.json",
    "data_path_map": _DATA_PATH_MAP,
}
TOOLCALL_MARKER_DELTA_S2NOCORR_VAL = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_marker/toolcall_marker_delta_s2nocorr_val.json",
    "data_path_map": _DATA_PATH_MAP,
}

# v3 = rung-1 matched-scale rebuild (2026-07-23): same generator, delta grammar,
# three changes -- seed magnitudes from the measured own-error distribution
# (--noise_median 0.185), arm mix shifted toward refine (--arm_probs), and
# decomposed-read correction turns (--decompose_reads, rendered by
# _adjust_value's per-turn flag). Separate files via --out_suffix _v3.
TOOLCALL_MARKER_DELTA_V3 = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_marker/toolcall_marker_delta_v3_train.json",
    "data_path_map": _DATA_PATH_MAP,
}
TOOLCALL_MARKER_DELTA_V3_VAL = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_marker/toolcall_marker_delta_v3_val.json",
    "data_path_map": _DATA_PATH_MAP,
}

# v3nd = v3 with the decomposed reads STRIPPED (2026-07-30), the isolating arm
# for the objection that the decomposition adds no information: the marker read
# is a verbatim copy of the place_marker argument already in context, the target
# read IS the placement task, and the delta is arithmetic on two numbers the
# model just emitted. So v3 bundles two changes (matched bands + decomposition)
# and only the bands are defensible on that argument. These files are v3 with
# `decompose` flipped to False on every adjust turn and NOTHING else touched, so
# the pair is a clean single-variable A/B on whether the bands alone were the fix.
TOOLCALL_MARKER_DELTA_V3ND = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_marker/toolcall_marker_delta_v3nd_train.json",
    "data_path_map": _DATA_PATH_MAP,
}
TOOLCALL_MARKER_DELTA_V3ND_VAL = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/toolcall_marker/toolcall_marker_delta_v3nd_val.json",
    "data_path_map": _DATA_PATH_MAP,
}

# Route-planning only (4 104 items). Separate entry so it can be upweighted
# independently of the full VLM3R VSI-Bench mix (which is 207 K items and
# dilutes route planning to ~2% of its gradient).
VLM3R_ROUTE_PLAN = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vlm3r_data/vsibench_train/merged_qa_route_plan_train.json",
    "data_path_map": _DATA_PATH_MAP,
}

VICA_322K_ARKIT = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vica-322k/arkitscenes/",
    "data_path_map": _DATA_PATH_MAP,
}
VICA_322K_ARKIT_BASE = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vica-322k/arkitscenes/base/",
    "data_path_map": _DATA_PATH_MAP,
}

VICA_322K_SNPP = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vica-322k/scannetpp/",
    "data_path_map": _DATA_PATH_MAP,
}
VICA_322K_SNPP_BASE = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vica-322k/scannetpp/base/",
    "data_path_map": _DATA_PATH_MAP,
}

VICA_322K_SCANNET = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vica-322k/scannet/",
    "data_path_map": _DATA_PATH_MAP,
}
VICA_322K_SCANNET_BASE = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/vica-322k/scannet/base/",
    "data_path_map": _DATA_PATH_MAP,
}

SPATIALLADDER_26K = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/spatialladder-26k/spld_spatial_data.jsonl",
    "data_path": f"{_DATA_ROOT}/scannet/scannet_preprocessed/",
}

SPBENCH = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/spbench/",
    "data_path": f"{_DATA_ROOT}/scannet/scannet_preprocessed/",
}

SCANREFER_TRAIN = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/scanrefer/scanrefer_train.jsonl",
    "data_path": f"{_DATA_ROOT}/scannet/scannet_preprocessed/",
}

SCANREFER_VAL = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/scanrefer/scanrefer_val.jsonl",
    "data_path": f"{_DATA_ROOT}/scannet/scannet_preprocessed/",
}

MULTI3DREFER = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/multi3drefer/multi3drefer_val.jsonl",
    "data_path": f"{_DATA_ROOT}/scannet/scannet_preprocessed/",
}

MULTI3DREFER_TRAIN = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/multi3drefer/multi3drefer_train.jsonl",
    "data_path": f"{_DATA_ROOT}/scannet/scannet_preprocessed/",
}

# Val-leakage-filtered ReferIt3D variants. Raw nr3d.jsonl / sr3d.jsonl share
# 130 / 116 of the 141 ScanRefer val scenes (which equal Multi3DRefer val), so
# they MUST NOT be used directly in training. The _train files below are
# produced by scripts/filter_referit3d_val_leakage.py and exclude every
# scanrefer_val scene. Use these in any grounding training mix.
NR3D_TRAIN = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/nr3d/nr3d_train.jsonl",
    "data_path": f"{_DATA_ROOT}/scannet/scannet_preprocessed/",
}

SR3D_TRAIN = {
    "annotation_path": f"{_DATA_ROOT}/vlm_annotations/sr3d/sr3d_train.jsonl",
    "data_path": f"{_DATA_ROOT}/scannet/scannet_preprocessed/",
}

# On-the-fly geometric probing dataset.
# Stub entry: SpatialPretrainingDataset owns its own scene list (sourced from
# vica_scannet_base) and generates synthetic Q-A pairs per scene per epoch.
GEOMETRIC_PROBING = {
    "annotation_path_train": None,
    "annotation_path_val":   None,
}

# Generic self-contained single-frame RGB-D QA. Each annotation item carries its
# OWN frame (rgb + metric-depth npy), a 4x4 camera-to-world pose, pinhole
# intrinsics, and QA -- there is no shared scene directory. With one frame the
# canvas origin defaults to that camera position (get_scene_center of a single
# pose), so grounding answers stored in world coords are re-centered to the
# camera exactly like the multi-frame grounding datasets. The annotation path is
# external (an experiment exports ONECANVAS_SINGLE_FRAME_QA_JSONL) so onecanvas
# stays generic; the agentic-onecanvas B1K reach SFT is the first consumer.
SINGLE_FRAME_QA = {
    "annotation_path": os.environ.get("ONECANVAS_SINGLE_FRAME_QA_JSONL", ""),
    "single_frame": True,
}

data_dict = {
    "scanqa": SCANQA,
    "single_frame_qa": SINGLE_FRAME_QA,
    "sqa3d": SQA3D,
    "sqa3d_agent_pose": SQA3D_AGENT_POSE,
    "mv_scanqa": MV_SCANQA,
    "vsi_bench": VSI_BENCH,
    "vlm3r_vsibench": VLM3R_VSIBENCH,
    "toolcall_matched": TOOLCALL_MATCHED,
    "toolcall_matched_val": TOOLCALL_MATCHED_VAL,
    "toolcall_marker": TOOLCALL_MARKER,
    "toolcall_marker_val": TOOLCALL_MARKER_VAL,
    "toolcall_marker_delta": TOOLCALL_MARKER_DELTA,
    "toolcall_marker_delta_val": TOOLCALL_MARKER_DELTA_VAL,
    "toolcall_marker_delta_v3": TOOLCALL_MARKER_DELTA_V3,
    "toolcall_marker_delta_v3_val": TOOLCALL_MARKER_DELTA_V3_VAL,
    "toolcall_marker_delta_v3nd": TOOLCALL_MARKER_DELTA_V3ND,
    "toolcall_marker_delta_v3nd_val": TOOLCALL_MARKER_DELTA_V3ND_VAL,
    "toolcall_marker_delta_s2corr": TOOLCALL_MARKER_DELTA_S2CORR,
    "toolcall_marker_delta_s2corr_val": TOOLCALL_MARKER_DELTA_S2CORR_VAL,
    "toolcall_marker_delta_s2nocorr": TOOLCALL_MARKER_DELTA_S2NOCORR,
    "toolcall_marker_delta_s2nocorr_val": TOOLCALL_MARKER_DELTA_S2NOCORR_VAL,
    "vlm3r_route_plan": VLM3R_ROUTE_PLAN,
    "vica_arkit": VICA_322K_ARKIT,
    "vica_arkit_base": VICA_322K_ARKIT_BASE,
    "vica_snpp": VICA_322K_SNPP,
    "vica_snpp_base": VICA_322K_SNPP_BASE,
    "vica_scannet": VICA_322K_SCANNET,
    "vica_scannet_base": VICA_322K_SCANNET_BASE,
    "spatialladder_26k": SPATIALLADDER_26K,
    "spbench": SPBENCH,
    "scanrefer_train": SCANREFER_TRAIN,
    "scanrefer_val": SCANREFER_VAL,
    "multi3drefer": MULTI3DREFER,
    "multi3drefer_train": MULTI3DREFER_TRAIN,
    "nr3d_train": NR3D_TRAIN,
    "sr3d_train": SR3D_TRAIN,
    "geometric_probing": GEOMETRIC_PROBING,
}


def parse_sampling_rate(dataset_name):
    match = re.search(r"%(\d+)$", dataset_name)
    if match:
        return int(match.group(1)) / 100.0
    return 1.0


def parse_dataset_weight(dataset_name):
    """Parse @N suffix → float weight (e.g. @7.8, @0.74). Returns None if absent."""
    match = re.search(r"@([\d.]+)$", dataset_name)
    return float(match.group(1)) if match else None


def data_list(dataset_names):
    config_list = []
    for dataset_name in dataset_names:
        weight = parse_dataset_weight(dataset_name)
        sampling_rate = parse_sampling_rate(dataset_name) if weight is None else 1.0
        clean_name = re.sub(r"[@%][\d.]+$", "", dataset_name)
        if clean_name not in data_dict:
            raise ValueError(f"do not find {clean_name}")
        config = data_dict[clean_name].copy()
        if weight is not None:
            config["dataset_weight"] = weight
        else:
            config["sampling_rate"] = sampling_rate
        config_list.append(config)
    return config_list


if __name__ == "__main__":
    dataset_names = ["sqa3d"]
    configs = data_list(dataset_names)
    for config in configs:
        print(config)
