"""Unified precompute pipeline for scene preprocessing.

One CLI that runs any subset of:

  --nonaligned   Predicted-pose DA3 geometry  (da3_geometry_*_metric.pt)
  --aligned      GT-pose-aligned DA3 geometry (da3_geometry_*_metric_aligned.pt)
                 — uses GT poses; depths/intrinsics inherited from nonaligned
                   if it exists, otherwise nonaligned is generated first.
  --features     Qwen visual features         (qwen3_vl_features_balanced_64*.pt)
  --verify       Comprehensive consistency check; --delete to clean stale files

The loop is per-scene: every requested phase finishes for one scene before
moving to the next, so a parallel training run never sees a half-processed
scene.

Who consumes each output family (training/onecanvas/data/data_processor_3d.py):

  da3_geometry_balanced_256[_crop003]_metric.pt
      The default QA-path geometry: `_geometry_candidates(wants_aligned=False)`
      primary list (crop003 name for ScanNet, plain name for ScanNet++ /
      ARKitScenes). Also the last-ditch fallback for every predicted-geometry
      eval arm, and the pose source for the DA3_FALLBACK_SCENES below.
  da3_geometry_balanced_256[_crop003]_metric_aligned.pt
      The grounding path: `_geometry_candidates(wants_aligned=True)`.
      GT poses, DA3 depths/intrinsics.
  qwen3_vl_features_balanced_64*.pt
      NOT read by any loader path in this release. The QA dataloader returns raw
      pixel_values and the vision tower runs live inside forward() (the
      "PRE-PATH-A" block in model_adapters/qwen3_vl/model.py), so --features
      writes files nothing consumes. Do not spend GPU hours on it expecting an
      eval or a training run to need them; neither does.
  da3_geometry_balanced_256[_crop003].pt (--no_metric)
      NOT read by any loader path; manual loader change required.

Seven ScanNet++ iPhone scenes REQUIRE the nonaligned _metric.pt even on the
GT-pose path (`--use_gt_all True`): their ARKit GT pose tracks diverged during
capture (worst: 189 km trajectory span), so the loader forces the DA3-predicted
poses for them (DA3_FALLBACK_SCENES in data_processor_3d.py: 7dab70c8c8,
d755b3d9d8, 120acffd90, cc0aa81452, 46001f434d, ab4f373966, 02a980c994; the
last has no iPhone RGB extracted and is dropped rather than rescued). See
docs/bad_scenes.md.

GPU requirement: --nonaligned loads the DA3 nested-giant model and --features
loads a Qwen3-VL 8B tower; both need a CUDA GPU. Requesting depth + features
in one invocation on a GPU under 40 GB may OOM (a warning suggests the split).
--aligned alone and --verify are CPU-only.

Metric-model pin: any output whose filename carries `_metric` comes from the
DA3 model id `depth-anything/DA3NESTED-GIANT-LARGE-1.1` (DA3_MODEL_METRIC).
The non-nested DA3-Large is NOT metric; its output is only ever written under
the suffix-free `--no_metric` names, and an assert enforces the pairing.

Release-port addition: each nonaligned geometry write now also drops a
provenance sidecar `<output>.pt.json` recording model_id (plus frame counts
and crop ratio). The pre-release producer wrote no sidecar; the .pt payload
itself is unchanged.

Example commands:

  python scripts/precompute.py --dataset scannet --nonaligned --aligned --features
  python scripts/precompute.py --dataset scannetpp --nonaligned --aligned --features
  python scripts/precompute.py --dataset arkitscenes --nonaligned --features --split Training

Dataset roots resolve through onecanvas.data (ONECANVAS_DATA_ROOT env var,
else a `datasets/` directory sitting next to the repo root).

Geometry filenames this script CAN produce, of the loader's candidate set:
  da3_geometry_balanced_256_crop003_metric.pt          (scannet, --nonaligned)
  da3_geometry_balanced_256_metric.pt                  (scannetpp / scannetpp_dslr / arkitscenes, --nonaligned)
  da3_geometry_balanced_256_crop003_metric_aligned.pt  (scannet, --aligned)
  da3_geometry_balanced_256_metric_aligned.pt          (scannetpp / scannetpp_dslr / arkitscenes, --aligned)
Filenames in `_geometry_candidates` this script CANNOT produce — the
predicted-geometry eval arms, generated by separate tools
(agentic-onecanvas predgeo / dvlt_da3anchor / predgeo_scale_calibrate
pipelines), listed here so nobody hunts for a flag that doesn't exist:
  {da3,mapanything,dvlt}_geometry_eval32_crop003_metric.pt
  {da3,mapanything,dvlt}_geometry_eval32_metric.pt
  {da3,mapanything,dvlt}_geometry_spbench_crop003_metric.pt
  {da3,dvlt}_geometry_eval32ctx256_crop003_metric.pt
  {da3,dvlt}_geometry_eval32ctx256_metric.pt
  {da3,dvlt}_geometry_spbenchctx256_crop003_metric.pt
  dvlt_geometry_eval32ctx256_upright_hires_metric.pt
  dvlt_geometry_eval32ctx256_hires_metric.pt
  {da3,dvlt}_geometry_eval32ctx_upright_hires_metric.pt
  {da3,dvlt}_geometry_eval32ctx_hires_metric.pt
  {da3,dvlt}_geometry_eval32_hires_metric.pt
  {da3,dvlt}_geometry_eval32ctx_hires_crop003_metric.pt
  {da3,dvlt}_geometry_spbenchctx_hires_crop003_metric.pt
  da3_geometry_eval32ctx_hires_{scalecal,scaleoracle}_crop003_metric.pt
  da3_geometry_spbenchctx_hires_{scalecal,scaleoracle}_crop003_metric.pt
  da3_geometry_eval32_hires32_crop003_metric.pt
  da3_geometry_eval32_upright_hires_metric.pt
"""

import argparse
import atexit
import gc
import json
import os
import random
import signal
import sys
import time
import traceback
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
import torch
from PIL import Image

# Add repo root + training/ to sys.path so we can import inference / geometry /
# onecanvas (which lives under training/onecanvas).
_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))
sys.path.insert(0, str(_REPO_ROOT / "training"))

from inference import _compute_da3_geometry  # noqa: E402
from model_adapters.qwen3_vl.feature_extraction import split_image_features  # noqa: E402
from onecanvas.data import _DATA_PATH_MAP  # noqa: E402

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# PINNED: the metric arm. Only the NESTED giant DA3 is metric; every filename
# carrying `_metric` must come from this id (asserted in nonaligned_scene).
DA3_MODEL_METRIC = "depth-anything/DA3NESTED-GIANT-LARGE-1.1"
DA3_MODEL_NOMETRIC = "depth-anything/DA3-Large"

# How long an .inprogress lock can sit on disk before we assume the writer
# died and reclaim it. Longer than any single-scene depth pass.
STALE_LOCK_AGE_SECONDS = 30 * 60

# Pre-flight VRAM threshold for the both-phases warning.
SMALL_GPU_BYTES = 40 * 1024 ** 3


# ---------------------------------------------------------------------------
# Lock infrastructure (process-wide tracking + signal/atexit cleanup)
# ---------------------------------------------------------------------------

_ACTIVE_LOCKS: set[str] = set()


def _release_all_locks():
    """Unlink every lock currently held by this process. Safe to call twice."""
    for path in list(_ACTIVE_LOCKS):
        try:
            if os.path.exists(path):
                os.remove(path)
        except OSError:
            pass
        _ACTIVE_LOCKS.discard(path)


def _signal_handler(signum, frame):
    _release_all_locks()
    # Restore default handler and re-raise so the process actually exits.
    signal.signal(signum, signal.SIG_DFL)
    os.kill(os.getpid(), signum)


def _install_signal_handlers():
    atexit.register(_release_all_locks)
    signal.signal(signal.SIGINT, _signal_handler)
    signal.signal(signal.SIGTERM, _signal_handler)


def _acquire_lock(target_path: str) -> bool:
    """Try to acquire a `<target>.inprogress` lockfile.

    Returns True on success, False if another process holds it. Reclaims the
    lock if it is older than STALE_LOCK_AGE_SECONDS (orphaned writer).
    """
    lock_path = target_path + ".inprogress"

    # Reclaim a stale lock from a dead writer.
    if os.path.exists(lock_path):
        try:
            age = time.time() - os.path.getmtime(lock_path)
        except OSError:
            age = 0
        if age > STALE_LOCK_AGE_SECONDS:
            print(f"  reclaiming stale lock ({age/60:.1f} min old): {lock_path}")
            try:
                os.remove(lock_path)
            except OSError:
                pass

    try:
        # O_EXCL atomic create — fails if another process won the race.
        open(lock_path, "x").close()
    except FileExistsError:
        return False

    _ACTIVE_LOCKS.add(lock_path)
    return True


def _release_lock(target_path: str):
    lock_path = target_path + ".inprogress"
    try:
        if os.path.exists(lock_path):
            os.remove(lock_path)
    except OSError:
        pass
    _ACTIVE_LOCKS.discard(lock_path)


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _crop_borders(img: Image.Image, ratio: float) -> Image.Image:
    """Remove ratio*size pixels from each side to strip lens-distortion borders."""
    if ratio <= 0:
        return img
    w, h = img.size
    cx = int(round(w * ratio))
    cy = int(round(h * ratio))
    return img.crop((cx, cy, w - cx, h - cy))


def uniform_sample(items, n):
    """Return n items sampled as uniformly as possible from items via linspace."""
    if n >= len(items):
        return list(items)
    indices = np.linspace(0, len(items) - 1, n, dtype=int)
    return [items[i] for i in indices]


def feature_subsample_indices(n_depth: int, n_feature: int) -> list[int]:
    """Indices in the depth-frame list that become feature frames.

    The feature frames are a uniform subsample of the depth frames chosen so
    the set is divisible into 16 / 32 / 48 by simple slicing.
    """
    return np.linspace(0, n_depth - 1, n_feature, dtype=int).tolist()


def cleanup_gpu():
    gc.collect()
    if torch.cuda.is_available():
        with torch.no_grad():
            torch.cuda.empty_cache()


# ---------------------------------------------------------------------------
# Per-dataset scene discovery
# ---------------------------------------------------------------------------


def _discover_scannet(img_root):
    """Yield (scene_id, scene_root, color_files) for ScanNet scenes."""
    if not os.path.isdir(img_root):
        return
    for scene_id in sorted(os.listdir(img_root)):
        scene_root = os.path.join(img_root, scene_id)
        if not os.path.isdir(scene_root):
            continue
        color_path = os.path.join(scene_root, "color")
        if not os.path.isdir(color_path):
            continue
        color_files = sorted(Path(color_path).glob("*.jpg"))
        if not color_files:
            continue
        yield scene_id, scene_root, color_files


def _discover_arkitscenes(img_root):
    """Yield (scene_id, scene_root, color_files) for ARKitScenes."""
    if not os.path.isdir(img_root):
        return
    for scene_id in sorted(os.listdir(img_root)):
        scene_root = os.path.join(img_root, scene_id)
        if not os.path.isdir(scene_root):
            continue
        vga_dir = os.path.join(scene_root, "vga_wide")
        if not os.path.isdir(vga_dir):
            continue
        color_files = sorted(Path(vga_dir).glob("*.png"))
        if not color_files:
            continue
        yield scene_id, scene_root, color_files


def _discover_scannetpp(img_root):
    """Yield (scene_id, iphone_dir, color_files) for ScanNet++ iPhone scenes."""
    if not os.path.isdir(img_root):
        return
    for scene_id in sorted(os.listdir(img_root)):
        iphone_dir = os.path.join(img_root, scene_id, "iphone")
        rgb_dir = os.path.join(iphone_dir, "rgb")
        if not os.path.isdir(rgb_dir):
            continue
        color_files = sorted(Path(rgb_dir).glob("*.jpg"))
        if not color_files:
            continue
        yield scene_id, iphone_dir, color_files


def _discover_scannetpp_dslr(img_root):
    """Yield (scene_id, dslr_dir, color_files) for ScanNet++ DSLR scenes."""
    if not os.path.isdir(img_root):
        return
    for scene_id in sorted(os.listdir(img_root)):
        dslr_dir = os.path.join(img_root, scene_id, "dslr")
        img_dir = os.path.join(dslr_dir, "resized_undistorted_images_320x240")
        if not os.path.isdir(img_dir):
            continue
        color_files = sorted(Path(img_dir).glob("*.JPG"))
        if not color_files:
            color_files = sorted(Path(img_dir).glob("*.jpg"))
        if not color_files:
            continue
        yield scene_id, dslr_dir, color_files


# ---------------------------------------------------------------------------
# GT-pose loaders for aligned mode
# ---------------------------------------------------------------------------


def _parse_scannet_axis_alignment(scene_dir: str, scene_id: str) -> Optional[torch.Tensor]:
    """Parse the 4x4 axisAlignment matrix from <scene_dir>/<scene_id>.txt."""
    info_path = os.path.join(scene_dir, f"{scene_id}.txt")
    if not os.path.exists(info_path):
        return None
    with open(info_path) as f:
        for line in f:
            if line.strip().startswith("axisAlignment"):
                vals = [float(x) for x in line.split("=")[1].split()]
                if len(vals) != 16:
                    return None
                return torch.tensor(vals, dtype=torch.float32).reshape(4, 4)
    return None


def _load_scannet_gt_poses(scene_dir: str, scene_id: str) -> Dict[str, torch.Tensor]:
    """Return {stem: 4x4 axis-aligned pose} for a ScanNet scene.

    Recipe (verified against existing _aligned.pt): pose_aligned = axisAlignment @ pose/<stem>.txt.
    """
    axis = _parse_scannet_axis_alignment(scene_dir, scene_id)
    if axis is None:
        raise FileNotFoundError(
            f"axisAlignment not found in {scene_dir}/{scene_id}.txt"
        )

    pose_dir = os.path.join(scene_dir, "pose")
    if not os.path.isdir(pose_dir):
        raise FileNotFoundError(f"pose/ directory missing for {scene_id}")

    poses: Dict[str, torch.Tensor] = {}
    for p in sorted(Path(pose_dir).glob("*.txt")):
        try:
            mat = torch.from_numpy(np.loadtxt(str(p))).float()
        except Exception:
            continue
        if mat.shape != (4, 4) or not torch.isfinite(mat).all():
            continue
        poses[p.stem] = axis @ mat
    return poses


def _load_scannetpp_gt_poses(scene_dir: str, scene_id: str) -> Dict[str, torch.Tensor]:
    """Return {stem: 4x4 pose} for a ScanNet++ iPhone scene.

    Recipe (verified): use the raw `pose` field of pose_intrinsic_imu.json
    directly. The existing _aligned.pt files match this exactly.

    THIS DELIBERATELY STAYS IN THE ARKIT FRAME, unlike the GT-calib path in
    data_processor_3d, which now applies the per-scene mesh registration from
    onecanvas.data.scannetpp_registration. The two do not conflict. What the
    registration corrects is yaw and translation: measured over 614 registered
    scenes the R_yz below gets gravity right to a median of 0.49 degrees, with
    99% under 5. A canvas carrying no object annotations is therefore equally
    good in either frame, because only annotations care where the origin and
    the yaw sit, and regenerating these files would invalidate every cached
    geometry file for no gain.

    The line not to cross: anything placing MESH-FRAME annotations on a canvas
    must come through the GT-calib path, never through these files.
    """
    json_path = os.path.join(scene_dir, "pose_intrinsic_imu.json")
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"pose_intrinsic_imu.json missing for {scene_id}")
    with open(json_path) as f:
        data = json.load(f)

    # ScanNet++ iPhone JSON poses (empirically determined):
    #   - camera-to-world
    #   - camera frame: OpenCV-compatible (no cam flip needed; -R[:,1] ends
    #     up = -world_z = down in z-up world only with this composition)
    #   - world: y-up → apply R_yz = Rx(+90°) to get z-up.
    # Final: T_final = R_yz @ T_raw.
    R_yz = torch.tensor([[1.0, 0, 0, 0],
                         [0, 0, -1, 0],
                         [0, 1, 0, 0],
                         [0, 0, 0, 1.0]])
    poses: Dict[str, torch.Tensor] = {}
    for stem, entry in data.items():
        if "pose" not in entry:
            continue
        mat = torch.tensor(entry["pose"], dtype=torch.float32)
        if mat.shape != (4, 4) or not torch.isfinite(mat).all():
            continue
        poses[stem] = R_yz @ mat
    return poses


def _load_scannetpp_dslr_gt_poses(scene_dir: str, scene_id: str) -> Dict[str, torch.Tensor]:
    """Return {stem: 4x4 pose} for a ScanNet++ DSLR scene.

    Loads poses from nerfstudio/transforms_undistorted.json (camera-to-world,
    nerfstudio convention) and applies gravity alignment + recentering — the
    same transform that _compute_da3_geometry applies to DA3 predicted poses.

    Recipe (verified against existing on-disk _aligned.pt files):
      1. Collect all frame transform_matrices from the JSON.
      2. Compute average camera-down direction (column 1 of each R).
      3. Build R_gravity that rotates avg_down -> [0, 0, -1].
      4. Recentre: subtract mean camera translation, then rotate.
      => T_aligned = [[R_gravity, -R_gravity @ centroid], [0,0,0,1]] @ T_json
    """
    json_path = os.path.join(scene_dir, "nerfstudio", "transforms_undistorted.json")
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"nerfstudio/transforms_undistorted.json missing for {scene_id}")
    with open(json_path) as f:
        data = json.load(f)

    def _parse_frames(frame_list):
        out = {}
        for frame in frame_list:
            stem = os.path.splitext(os.path.basename(frame.get("file_path", "")))[0]
            mat = frame.get("transform_matrix")
            if mat is None or stem == "":
                continue
            t = torch.tensor(mat, dtype=torch.float32)
            if t.shape == (4, 4) and torch.isfinite(t).all():
                out[stem] = t
        return out

    # Use only train frames for gravity alignment (test_frames have inconsistent
    # poses in some scenes and must not be included in the reference set).
    train_raw = _parse_frames(data.get("frames", []))
    test_raw  = _parse_frames(data.get("test_frames", []))
    raw = {**train_raw, **test_raw}

    if not train_raw:
        return {}

    # --- gravity alignment + recentering (computed from train frames only) ---
    poses = list(train_raw.values())
    Rs = torch.stack([p[:3, :3] for p in poses])          # [N, 3, 3]
    ts = torch.stack([p[:3, 3]  for p in poses])          # [N, 3]

    avg_down = Rs[:, :, 1].mean(dim=0)                    # mean camera Y (down)
    avg_down = avg_down / (avg_down.norm() + 1e-12)
    target = torch.tensor([0.0, 0.0, -1.0])

    v = torch.linalg.cross(avg_down, target)
    c = torch.dot(avg_down, target).item()
    s = v.norm().item()

    if s > 1e-6:
        kmat = torch.tensor([
            [0.0,   -v[2],  v[1]],
            [v[2],   0.0,  -v[0]],
            [-v[1],  v[0],  0.0],
        ])
        R_grav = torch.eye(3) + kmat + kmat @ kmat * ((1 - c) / (s ** 2))
    else:
        R_grav = torch.eye(3)

    centroid = ts.mean(dim=0)                              # [3]

    aligned: Dict[str, torch.Tensor] = {}
    for stem, p in raw.items():
        out = torch.eye(4, dtype=torch.float32)
        out[:3, :3] = R_grav @ p[:3, :3]
        out[:3, 3]  = R_grav @ (p[:3, 3] - centroid)
        aligned[stem] = out
    return aligned


def _load_arkitscenes_gt_poses(scene_dir: str, scene_id: str) -> Dict[str, torch.Tensor]:
    """Return {stem: 4x4 camera-to-world pose in z-up frame} for an ARKitScenes scene.

    Reads lowres_wide.traj (axis-angle + translation, Apple y-up convention),
    matches timestamps to vga_wide image stems by nearest-neighbour (tolerance
    100 ms), and converts to z-up via Rx(+90°).
    """
    traj_path = os.path.join(scene_dir, "lowres_wide.traj")
    if not os.path.exists(traj_path):
        raise FileNotFoundError(f"lowres_wide.traj missing for {scene_id}")

    # Parse traj: each line is "timestamp rx ry rz tx ty tz"
    # (rx ry rz) = axis-angle in radians, (tx ty tz) = translation in metres.
    traj_ts: list = []
    traj_T:  list = []
    with open(traj_path) as fh:
        for line in fh:
            parts = line.strip().split()
            if len(parts) != 7:
                continue
            ts = float(parts[0])
            aa = np.array([float(x) for x in parts[1:4]], dtype=np.float64)
            t  = np.array([float(x) for x in parts[4:7]], dtype=np.float64)
            angle = np.linalg.norm(aa)
            if angle > 1e-8:
                axis = aa / angle
                K = np.array([[0, -axis[2], axis[1]],
                               [axis[2], 0, -axis[0]],
                               [-axis[1], axis[0], 0]])
                R = np.eye(3) + np.sin(angle) * K + (1 - np.cos(angle)) * (K @ K)
            else:
                R = np.eye(3)
            T = np.eye(4, dtype=np.float64)
            T[:3, :3] = R
            T[:3, 3]  = t
            traj_ts.append(ts)
            traj_T.append(T)

    if not traj_ts:
        raise ValueError(f"Empty or unparseable traj file for {scene_id}")

    traj_ts_arr = np.array(traj_ts)

    # Rx(+90°): rotates Apple y-up world to z-up.
    R_yz = np.array([[1, 0,  0, 0],
                     [0, 0, -1, 0],
                     [0, 1,  0, 0],
                     [0, 0,  0, 1]], dtype=np.float64)

    vga_dir = os.path.join(scene_dir, "vga_wide")
    if not os.path.isdir(vga_dir):
        raise FileNotFoundError(f"vga_wide/ missing for {scene_id}")

    prefix = scene_id + "_"
    poses: Dict[str, torch.Tensor] = {}
    for p in sorted(Path(vga_dir).glob("*.png")):
        stem = p.stem
        if not stem.startswith(prefix):
            continue
        try:
            ts = float(stem[len(prefix):])
        except ValueError:
            continue
        idx = int(np.abs(traj_ts_arr - ts).argmin())
        if abs(traj_ts_arr[idx] - ts) > 0.1:   # 100 ms tolerance
            continue
        # ARKit lowres_wide.traj (empirically verified):
        #   - world-to-camera extrinsic (invert for c2w)
        #   - world already z-up
        #   - cam frame already OpenCV-compatible (NO cam flip needed;
        #     applying C flips world up/down wrong)
        poses[stem] = torch.from_numpy(np.linalg.inv(traj_T[idx])).float()

    return poses


# ---------------------------------------------------------------------------
# Dataset configuration (one dict, replaces the three duplicated configs)
# ---------------------------------------------------------------------------

DATASET_CONFIGS: Dict[str, Dict[str, Any]] = {
    "scannet": {
        "root": _DATA_PATH_MAP["scannet"],
        "splits": None,
        "border_crop_ratio": 0.03,
        "scene_subdir_fn": None,
        "discover_fn": _discover_scannet,
        "gt_pose_loader": _load_scannet_gt_poses,
        "depth": {
            "img_subdir": "color", "img_ext": ".jpg",
            "max_depth_frames": 256, "max_feature_frames": 64,
            "target_nonaligned": "da3_geometry_balanced_256_crop003_metric.pt",
            "target_nonaligned_nometric": "da3_geometry_balanced_256_crop003.pt",
            "target_aligned": "da3_geometry_balanced_256_crop003_metric_aligned.pt",
            "stale_files": [
                "da3_geometry.pt",
                "qwen3_vl_features_aggregated.pt",
            ],
        },
        "features": {
            "img_subdir_default": "color_320x240", "img_ext": ".jpg",
            "output_qwen3_vl": "qwen3_vl_features_balanced_64_crop003.pt",
            "output_qwen3_5":  "qwen3_5_features_balanced_64_crop003.pt",
        },
        "verify_color_subdir": "color", "verify_color_ext": "*.jpg",
        "resized_subdirs": ["color_320x240", "color_640x480"],
    },
    "arkitscenes": {
        "root": _DATA_PATH_MAP["arkitscenes"],
        "splits": ["Training", "Validation"],
        "border_crop_ratio": 0.0,
        "scene_subdir_fn": None,
        "discover_fn": _discover_arkitscenes,
        "gt_pose_loader": _load_arkitscenes_gt_poses,
        "depth": {
            "img_subdir": "vga_wide", "img_ext": ".png",
            "max_depth_frames": 256, "max_feature_frames": 64,
            "target_nonaligned": "da3_geometry_balanced_256_metric.pt",
            "target_nonaligned_nometric": "da3_geometry_balanced_256.pt",
            "target_aligned": "da3_geometry_balanced_256_metric_aligned.pt",
            "stale_files": [],
        },
        "features": {
            "img_subdir_default": "vga_wide_320x240", "img_ext": ".png",
            "output_qwen3_vl": "qwen3_vl_features_balanced_64.pt",
            "output_qwen3_5":  "qwen3_5_features_balanced_64.pt",
        },
        "verify_color_subdir": "vga_wide", "verify_color_ext": "*.png",
        "resized_subdirs": ["vga_wide_320x240"],
    },
    "scannetpp": {
        "root": _DATA_PATH_MAP["scannetpp"],
        "splits": None,
        "border_crop_ratio": 0.0,
        "scene_subdir_fn": lambda sid: "iphone",
        "discover_fn": _discover_scannetpp,
        "gt_pose_loader": _load_scannetpp_gt_poses,
        "depth": {
            "img_subdir": "iphone/rgb", "img_ext": ".jpg",
            "max_depth_frames": 256, "max_feature_frames": 64,
            "target_nonaligned": "da3_geometry_balanced_256_metric.pt",
            "target_nonaligned_nometric": "da3_geometry_balanced_256.pt",
            "target_aligned": "da3_geometry_balanced_256_metric_aligned.pt",
            "stale_files": [],
        },
        "features": {
            "img_subdir_default": "rgb_320x240", "img_ext": ".jpg",
            "output_qwen3_vl": "qwen3_vl_features_balanced_64.pt",
            "output_qwen3_5":  "qwen3_5_features_balanced_64.pt",
        },
        "verify_color_subdir": "iphone/rgb", "verify_color_ext": "*.jpg",
        "resized_subdirs": ["iphone/rgb_320x240", "iphone/rgb_640x480"],
    },
    "scannetpp_dslr": {
        "root": _DATA_PATH_MAP["scannetpp"],
        "splits": None,
        "border_crop_ratio": 0.0,
        "scene_subdir_fn": lambda sid: "dslr",
        "discover_fn": _discover_scannetpp_dslr,
        "gt_pose_loader": _load_scannetpp_dslr_gt_poses,
        "depth": {
            "img_subdir": "dslr/resized_undistorted_images_320x240", "img_ext": ".JPG",
            "max_depth_frames": 256, "max_feature_frames": 64,
            "target_nonaligned": "da3_geometry_balanced_256_metric.pt",
            "target_nonaligned_nometric": "da3_geometry_balanced_256.pt",
            "target_aligned": "da3_geometry_balanced_256_metric_aligned.pt",
            "stale_files": [],
        },
        "features": {
            "img_subdir_default": "resized_undistorted_images_320x240",
            "img_ext": ".JPG",
            "output_qwen3_vl": "qwen3_vl_features_balanced_64.pt",
            "output_qwen3_5":  "qwen3_5_features_balanced_64.pt",
        },
        "verify_color_subdir": "dslr/resized_undistorted_images_320x240", "verify_color_ext": "*.JPG",
        "resized_subdirs": ["dslr/resized_undistorted_images_320x240"],
    },
}


# ---------------------------------------------------------------------------
# Scene iteration (shared by all phases)
# ---------------------------------------------------------------------------


def _iter_scenes(cfg, args):
    """Yield (scene_id, scene_root, color_files) tuples for all phases.

    Honors --scenes / --scene_start / --scene_end / --shuffle / --split / cfg["splits"].
    `scene_root` is the directory where geometry/feature files live (already
    accounts for cfg["scene_subdir_fn"], so it points at iphone/ or dslr/ for
    ScanNet++).
    """
    if args.split is not None:
        roots = [cfg["root"].rstrip("/") + "/" + args.split + "/"]
    elif cfg.get("splits"):
        roots = [cfg["root"].rstrip("/") + "/" + s + "/" for s in cfg["splits"]]
    else:
        roots = [cfg["root"]]

    discover = cfg["discover_fn"]
    all_scenes: List[Tuple[str, str, List[Path]]] = []
    for root in roots:
        if not os.path.isdir(root):
            print(f"Skipping missing root: {root}")
            continue
        all_scenes.extend(discover(root))

    if args.shuffle:
        rng = random.Random(args.seed)
        rng.shuffle(all_scenes)

    if args.scene_start is not None or args.scene_end is not None:
        all_scenes = all_scenes[args.scene_start:args.scene_end]

    scenes_filter = set(args.scenes) if args.scenes else None
    for scene_id, scene_root, color_files in all_scenes:
        if scenes_filter and scene_id not in scenes_filter:
            continue
        yield scene_id, scene_root, color_files


# ---------------------------------------------------------------------------
# Filename resolution
# ---------------------------------------------------------------------------


def _resolve_depth_filename(cfg, args, variant: str) -> str:
    """variant in {"nonaligned", "aligned"}."""
    depth_cfg = cfg["depth"]
    if variant == "aligned":
        return depth_cfg["target_aligned"]
    if args.no_metric:
        return depth_cfg["target_nonaligned_nometric"]
    return depth_cfg["target_nonaligned"]


def _resolve_features_filename(cfg, args, model_id: str) -> str:
    """Output filename for the features phase, with resolution suffix logic
    matching the original features_saving.py:88-100 verbatim.
    """
    feat_cfg = cfg["features"]
    is_qwen3_vl = "qwen3-vl" in model_id.lower() or "qwen3_vl" in model_id.lower()
    base = feat_cfg["output_qwen3_vl"] if is_qwen3_vl else feat_cfg["output_qwen3_5"]

    res = args.feature_resolution
    if res and res != "320x240":
        if "320x240" in base:
            base = base.replace("320x240", res)
        else:
            stem, ext = os.path.splitext(base)
            base = f"{stem}_{res}{ext}"
    return base


def _resolve_features_img_subdir(cfg, args) -> str:
    feat_cfg = cfg["features"]
    subdir = feat_cfg["img_subdir_default"]
    res = args.feature_resolution
    if res and res != "320x240":
        if "320x240" in subdir:
            subdir = subdir.replace("320x240", res)
        else:
            subdir = f"{subdir}_{res}"
    return subdir


# ---------------------------------------------------------------------------
# Lazy model loaders
# ---------------------------------------------------------------------------


def load_da3_model(metric: bool):
    from depth_anything_3.api import DepthAnything3
    name = DA3_MODEL_METRIC if metric else DA3_MODEL_NOMETRIC
    print(f"Loading DepthAnything3 ({name})...")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = DepthAnything3.from_pretrained(name).to(device=device)
    return model


def load_feature_model(model_id: str):
    is_qwen3_vl = "qwen3-vl" in model_id.lower() or "qwen3_vl" in model_id.lower()
    print(f"Loading {model_id} ({'Qwen3-VL' if is_qwen3_vl else 'Qwen3.5'})...")
    if is_qwen3_vl:
        from transformers import Qwen3VLForConditionalGeneration
        model = Qwen3VLForConditionalGeneration.from_pretrained(
            model_id, torch_dtype=torch.bfloat16, device_map="auto",
        )
    else:
        from transformers import Qwen3_5ForConditionalGeneration
        model = Qwen3_5ForConditionalGeneration.from_pretrained(
            model_id, torch_dtype=torch.bfloat16, device_map="auto",
        )
    model.eval()
    from transformers import AutoProcessor
    processor = AutoProcessor.from_pretrained(model_id)
    # Disable processor-side resizing — features must be extracted at the
    # native image resolution.
    processor.image_processor.size["longest_edge"] = 67108864
    processor.image_processor.size["shortest_edge"] = 65536
    return model, processor


# ---------------------------------------------------------------------------
# Per-scene phase: NONALIGNED
# ---------------------------------------------------------------------------


def nonaligned_scene(cfg, args, scene_id, scene_root, color_files, da3_model, summary):
    """Compute predicted-pose DA3 metric geometry for one scene.

    Verbatim port of the original depth_saving.py main loop, scoped to a
    single scene and using the global lock infrastructure.
    """
    target_file = _resolve_depth_filename(cfg, args, "nonaligned")
    target_path = os.path.join(scene_root, target_file)
    model_id = DA3_MODEL_NOMETRIC if args.no_metric else DA3_MODEL_METRIC

    # CRITICAL PIN: any filename carrying `_metric` MUST come from the nested
    # metric DA3 (DA3_MODEL_METRIC). The non-nested DA3-Large is NOT metric;
    # writing its output under a `_metric` name would silently corrupt every
    # downstream metric read.
    assert ("_metric" in target_file) == (model_id == DA3_MODEL_METRIC), (
        f"metric-suffix / model mismatch: {target_file} vs {model_id}"
    )

    # Cleanup stale files listed in cfg["depth"]["stale_files"].
    for stale in cfg["depth"]["stale_files"]:
        stale_path = os.path.join(scene_root, stale)
        if os.path.exists(stale_path):
            os.remove(stale_path)
            print(f"  removed stale file: {stale}")

    # Skip if already done. Use a size threshold to catch obviously truncated
    # files without paying the cost of deserializing the full pickle on every
    # scene (torch.load is slow across thousands of existing scenes).
    if os.path.exists(target_path):
        if os.path.getsize(target_path) > 4096:
            summary["nonaligned_skipped"] += 1
            return
        print(f"  suspiciously small nonaligned file for {scene_id}, regenerating...")
        os.remove(target_path)

    if not _acquire_lock(target_path):
        print(f"  skipping {scene_id}: another process holds the lock")
        summary["nonaligned_skipped"] += 1
        return

    try:
        max_depth = cfg["depth"]["max_depth_frames"]
        max_feat = cfg["depth"]["max_feature_frames"]
        depth_files = uniform_sample(list(color_files), max_depth)
        feat_indices = feature_subsample_indices(len(depth_files), max_feat)
        feature_stems = [depth_files[i].stem for i in feat_indices]
        stems = [p.stem for p in depth_files]
        image_paths = [str(p) for p in depth_files]

        print(f"  [nonaligned] {len(image_paths)} depth frames, "
              f"{len(feature_stems)} feature frames")

        pil_images = []
        for p in image_paths:
            img = Image.open(p).convert("RGB")
            img = _crop_borders(img, cfg["border_crop_ratio"])
            pil_images.append(img)

        proj_depths, proj_poses, intrinsics = _compute_da3_geometry(pil_images, da3_model)

        scene_data = {}
        for i, stem in enumerate(stems):
            scene_data[stem] = {
                "depth": proj_depths[i].cpu(),
                "pose": proj_poses[i].cpu(),
                "intrinsics": intrinsics[i].cpu(),
            }
        scene_data["__feature_stems__"] = feature_stems

        torch.save(scene_data, target_path)

        # Provenance sidecar (release-port addition; the .pt payload above is
        # unchanged from the pre-release producer, which wrote no sidecar).
        with open(target_path + ".json", "w") as fh:
            json.dump({
                "model_id": model_id,
                "dataset": args.dataset,
                "scene_id": scene_id,
                "n_depth_frames": len(stems),
                "n_feature_frames": len(feature_stems),
                "border_crop_ratio": cfg["border_crop_ratio"],
                "created_unix": time.time(),
            }, fh, indent=2)

        print(f"  [nonaligned] saved -> {target_path}")
        summary["nonaligned_processed"] += 1
    except Exception:
        summary["nonaligned_errors"] += 1
        traceback.print_exc()
        raise
    finally:
        _release_lock(target_path)


# ---------------------------------------------------------------------------
# Per-scene phase: ALIGNED
# ---------------------------------------------------------------------------


def aligned_scene(cfg, args, scene_id, scene_root, color_files, da3_model, summary):
    """Build _aligned.pt by replacing poses in an existing _metric.pt with GT poses.

    Recipe (verified empirically against existing files):
      ScanNet:           pose_aligned[stem] = axisAlignment @ pose/<stem>.txt
      ScanNet++ iphone:  pose_aligned[stem] = pose_intrinsic_imu.json[stem]['pose']
      ScanNet++ dslr:    gravity-aligned + recentered from nerfstudio transforms
      ARKitScenes:       lowres_wide.traj nearest-ts match, y-up -> z-up via Rx(+90°)

    Depths, intrinsics, and __feature_stems__ are inherited from the existing
    nonaligned _metric.pt (verified bytewise identical between variants).
    """
    aligned_file = cfg["depth"]["target_aligned"]
    aligned_path = os.path.join(scene_root, aligned_file)
    nonaligned_file = cfg["depth"]["target_nonaligned"]
    nonaligned_path = os.path.join(scene_root, nonaligned_file)

    # Skip if already done.
    if os.path.exists(aligned_path):
        if os.path.getsize(aligned_path) > 4096:
            summary["aligned_skipped"] += 1
            return
        print(f"  suspiciously small aligned file for {scene_id}, regenerating...")
        os.remove(aligned_path)

    if not os.path.exists(nonaligned_path):
        print(f"  skipping {scene_id}: aligned requires existing {nonaligned_file} "
              f"(pass --nonaligned --aligned together)")
        summary["aligned_skipped"] += 1
        return

    if not _acquire_lock(aligned_path):
        print(f"  skipping {scene_id}: another process holds the aligned lock")
        summary["aligned_skipped"] += 1
        return

    try:
        nonaligned_data = torch.load(
            nonaligned_path, map_location="cpu", weights_only=False
        )
        gt_poses = cfg["gt_pose_loader"](scene_root, scene_id)

        existing_stems = [k for k in nonaligned_data.keys() if not k.startswith("__")]
        kept_stems = [s for s in existing_stems if s in gt_poses]
        n_dropped = len(existing_stems) - len(kept_stems)
        if n_dropped > 0:
            print(f"  [aligned] dropped {n_dropped}/{len(existing_stems)} frames "
                  f"missing GT poses")
        if n_dropped > len(existing_stems) * 0.5:
            raise RuntimeError(
                f"More than half the frames ({n_dropped}/{len(existing_stems)}) "
                f"have no GT pose; refusing to write a sparse aligned file."
            )

        scene_data = {}
        for stem in kept_stems:
            scene_data[stem] = {
                "depth": nonaligned_data[stem]["depth"],
                "pose": gt_poses[stem].cpu(),
                "intrinsics": nonaligned_data[stem]["intrinsics"],
            }

        # Inherit feature_stems but drop any that no longer have GT poses.
        feat_stems = nonaligned_data.get("__feature_stems__", [])
        feat_stems = [s for s in feat_stems if s in scene_data]
        scene_data["__feature_stems__"] = feat_stems

        torch.save(scene_data, aligned_path)
        print(f"  [aligned] saved {len(kept_stems)} frames -> {aligned_path}")
        summary["aligned_processed"] += 1
    except Exception:
        summary["aligned_errors"] += 1
        traceback.print_exc()
        raise
    finally:
        _release_lock(aligned_path)


# ---------------------------------------------------------------------------
# Per-scene phase: FEATURES
# ---------------------------------------------------------------------------


def get_batch_features(image_paths, border_crop_ratio, model, processor, merge_size):
    """Verbatim port of the original features_saving.py:161-194.

    model_adapters/qwen3_vl/model.py's decode-path feature reshaping mirrors
    the block below (the comment there cites scripts/precompute.py by line;
    the block starts at the `with torch.no_grad():` here).
    """
    images = [_crop_borders(Image.open(p).convert("RGB"), border_crop_ratio) for p in image_paths]
    inputs = processor(images=images, text=[""] * len(images), return_tensors="pt").to(model.device)

    with torch.no_grad():
        # No return_dict: 4.57.x's get_image_features does not accept it.
        # split_image_features normalizes the 4.57 tuple and the 5.x dataclass.
        image_outputs = model.model.get_image_features(
            inputs.pixel_values,
            inputs.image_grid_thw,
        )
        image_embeds_per_img, deepstack_features = split_image_features(image_outputs)

        h_feat = inputs.image_grid_thw[:, 1] // merge_size
        w_feat = inputs.image_grid_thw[:, 2] // merge_size
        tokens_per_img = (h_feat * w_feat).tolist()

        batch_results = []
        for i in range(len(image_paths)):
            h_i, w_i = int(h_feat[i]), int(w_feat[i])
            base_feat = image_embeds_per_img[i].view(h_i, w_i, -1).cpu()
            layers = [base_feat]

            if deepstack_features is not None:
                for layer_tensor in deepstack_features:
                    chunks = torch.split(layer_tensor, tokens_per_img, dim=0)
                    layers.append(chunks[i].view(h_i, w_i, -1).cpu())

            batch_results.append(torch.stack(layers, dim=0))

        return batch_results


def features_scene(cfg, args, scene_id, scene_root, color_files,
                   model, processor, merge_size, summary):
    """Extract Qwen visual features for one scene.

    Reads __feature_stems__ from whichever depth .pt is appropriate for the
    same-invocation phase flags. The feature file is variant-agnostic — both
    nonaligned and aligned share the same __feature_stems__ list.
    """
    output_file = _resolve_features_filename(cfg, args, args.model)
    output_path = os.path.join(scene_root, output_file)
    img_subdir = _resolve_features_img_subdir(cfg, args)
    img_ext = cfg["features"]["img_ext"]

    # Pick the geometry file to read __feature_stems__ from. Prefer whichever
    # variant the user is generating in the same invocation; fall back to
    # nonaligned, then aligned, then bail.
    candidates = []
    if args.aligned:
        candidates.append(cfg["depth"]["target_aligned"])
    if args.nonaligned or not args.aligned:
        candidates.append(cfg["depth"]["target_nonaligned"])
    candidates.append(cfg["depth"]["target_aligned"])
    if args.no_metric:
        candidates.append(cfg["depth"]["target_nonaligned_nometric"])
    seen = set()
    candidates = [c for c in candidates if c and not (c in seen or seen.add(c))]

    geometry_path = None
    for fn in candidates:
        p = os.path.join(scene_root, fn)
        if os.path.exists(p):
            geometry_path = p
            break

    if geometry_path is None:
        print(f"  [features] skipping {scene_id}: no geometry file found "
              f"(tried {candidates})")
        summary["features_missing_geometry"] += 1
        return

    if os.path.exists(output_path):
        summary["features_skipped"] += 1
        return

    if not _acquire_lock(output_path):
        print(f"  skipping {scene_id}: another process holds the features lock")
        summary["features_skipped"] += 1
        return

    try:
        try:
            geometry_data = torch.load(geometry_path, map_location="cpu", weights_only=False)
        except Exception as e:
            print(f"  [features] skipping {scene_id}: corrupt geometry ({e})")
            summary["features_corrupt_geometry"] += 1
            return

        valid_stems = (
            geometry_data["__feature_stems__"]
            if "__feature_stems__" in geometry_data
            else [k for k in geometry_data.keys() if not k.startswith("__")]
        )
        del geometry_data

        scene_features: Dict[str, torch.Tensor] = {}
        img_dir = os.path.join(scene_root, img_subdir)

        BATCH_SIZE = 50
        for i in range(0, len(valid_stems), BATCH_SIZE):
            batch_stems = valid_stems[i:i + BATCH_SIZE]
            batch_paths = [os.path.join(img_dir, f"{s}{img_ext}") for s in batch_stems]
            existing = [(idx, p) for idx, p in enumerate(batch_paths) if os.path.exists(p)]
            if not existing:
                continue
            proc_paths = [p for _, p in existing]
            proc_stems = [batch_stems[idx] for idx, _ in existing]
            features = get_batch_features(
                proc_paths, cfg["border_crop_ratio"], model, processor, merge_size,
            )
            for stem, feat in zip(proc_stems, features):
                scene_features[stem] = feat
            print(f"  [features] {scene_id}: {i + len(proc_stems)}/{len(valid_stems)}")

        if not scene_features:
            print(f"  [features] WARNING: no features produced for {scene_id} "
                  f"(check {img_dir}/ exists and contains {img_ext} files)")
            summary["features_no_output"] += 1
            return

        # Atomic write via temp + rename.
        temp_path = output_path + ".tmp"
        try:
            torch.save(scene_features, temp_path)
            torch.load(temp_path, map_location="cpu", mmap=True, weights_only=False)
            os.replace(temp_path, output_path)
            print(f"  [features] saved {len(scene_features)} frames -> {output_path}")
            summary["features_processed"] += 1
        except Exception:
            if os.path.exists(temp_path):
                os.remove(temp_path)
            raise
    except Exception:
        summary["features_errors"] += 1
        traceback.print_exc()
        raise
    finally:
        _release_lock(output_path)


# ---------------------------------------------------------------------------
# Per-scene phase: VERIFY
# ---------------------------------------------------------------------------


def _is_qwen_vl_filename(name: str) -> bool:
    return "qwen3_vl" in name


def _expected_layer_count(name: str) -> int:
    return 4 if _is_qwen_vl_filename(name) else 1


def verify_scene(cfg, args, scene_id, scene_root, color_files, summary, report_lines):
    """Run the full battery of consistency checks for one scene.

    Builds a per-scene status dict and appends a human-readable line to
    report_lines. With --delete, removes files that need regeneration.
    """
    issues: List[str] = []
    files_to_delete: List[str] = []

    # ---- A. Image-source consistency -------------------------------------
    n_color_native = len(color_files)
    color_subdir_path = (
        Path(cfg["root"]) / scene_id / cfg["verify_color_subdir"]
        if not cfg.get("scene_subdir_fn")
        else Path(scene_root).parent / cfg["verify_color_subdir"]
    )
    # Note: scene_root for ScanNet++ is .../<scene>/iphone, so its parent is
    # .../<scene>; verify_color_subdir is "iphone/rgb" which when joined to
    # parent gives .../<scene>/iphone/rgb. The above branch handles that.
    # The simplest robust resolution: derive from the parent of color_files[0].
    color_dir = color_files[0].parent if color_files else None

    parent_for_resized = (
        Path(scene_root).parent if cfg.get("scene_subdir_fn") else Path(scene_root)
    )
    for resized_subdir in cfg.get("resized_subdirs", []):
        # resized_subdir may be "iphone/rgb_320x240" — that's relative to scene
        # parent for ScanNet++, or relative to scene_root for ScanNet/ArkitScenes.
        resized_path = parent_for_resized / resized_subdir
        if resized_path.exists():
            n_resized = sum(1 for _ in resized_path.iterdir() if _.is_file())
            if n_resized != n_color_native:
                issues.append(
                    f"mismatched_resize:{resized_subdir}({n_resized}/{n_color_native})"
                )

    # ---- B/C. Depth file checks ------------------------------------------
    expected_stems = set(p.stem for p in uniform_sample(list(color_files),
                                                         cfg["depth"]["max_depth_frames"]))
    depth_status = {}
    depth_data_per_variant: Dict[str, Optional[dict]] = {}

    variants = [
        ("nonaligned", cfg["depth"]["target_nonaligned"]),
        ("aligned", cfg["depth"]["target_aligned"]),
    ]
    for variant, fname in variants:
        path = os.path.join(scene_root, fname)
        if not os.path.exists(path):
            depth_status[variant] = "missing"
            depth_data_per_variant[variant] = None
            continue
        try:
            size = os.path.getsize(path)
        except OSError:
            size = 0
        if size == 0:
            issues.append(f"corrupt_depth_{variant}:zero_byte")
            depth_status[variant] = "corrupt"
            files_to_delete.append(path)
            depth_data_per_variant[variant] = None
            continue
        try:
            data = torch.load(path, map_location="cpu", mmap=True, weights_only=False)
        except Exception as e:
            issues.append(f"corrupt_depth_{variant}:{type(e).__name__}")
            depth_status[variant] = "corrupt"
            files_to_delete.append(path)
            depth_data_per_variant[variant] = None
            continue

        depth_data_per_variant[variant] = data

        if "__feature_stems__" not in data:
            issues.append(f"legacy_depth_{variant}:no_feature_stems")
            depth_status[variant] = "legacy"
            files_to_delete.append(path)
            continue

        actual_stems = set(k for k in data.keys() if not k.startswith("__"))
        if actual_stems != expected_stems:
            n_overlap = len(actual_stems & expected_stems)
            issues.append(
                f"stale_depth_{variant}:n_actual={len(actual_stems)},"
                f"n_expected={len(expected_stems)},n_overlap={n_overlap}"
            )
            depth_status[variant] = "stale"
            files_to_delete.append(path)
            continue

        # Spot-check structure on a few frames.
        sample_keys = random.sample(list(actual_stems), min(5, len(actual_stems)))
        bad_struct = False
        for k in sample_keys:
            d = data[k]["depth"]
            p = data[k]["pose"]
            ki = data[k]["intrinsics"]
            if d.dim() != 2 or d.dtype != torch.uint16 or d.numel() == 0:
                bad_struct = True
                break
            if p.shape != (4, 4) or not torch.isfinite(p).all():
                bad_struct = True
                break
            if ki.shape != (4,) or not torch.isfinite(ki).all():
                bad_struct = True
                break
        if bad_struct:
            issues.append(f"corrupt_depth_{variant}:bad_frame_struct")
            depth_status[variant] = "corrupt"
            files_to_delete.append(path)
            continue

        depth_status[variant] = "ok"

    # Cross-variant consistency
    nd = depth_data_per_variant.get("nonaligned")
    ad = depth_data_per_variant.get("aligned")
    if nd is not None and ad is not None:
        nd_stems = nd.get("__feature_stems__")
        ad_stems = ad.get("__feature_stems__")
        if nd_stems != ad_stems:
            issues.append("cross_variant_stale:feature_stems_diverge")
            # Mark the older one for deletion.
            np_path = os.path.join(scene_root, cfg["depth"]["target_nonaligned"])
            ap_path = os.path.join(scene_root, cfg["depth"]["target_aligned"])
            try:
                older = np_path if os.path.getmtime(np_path) < os.path.getmtime(ap_path) else ap_path
                files_to_delete.append(older)
            except OSError:
                pass

    # ---- D. Feature file checks ------------------------------------------
    feat_cfg = cfg["features"]
    expected_feature_stems = None
    for variant_data in depth_data_per_variant.values():
        if variant_data is not None and "__feature_stems__" in variant_data:
            expected_feature_stems = variant_data["__feature_stems__"]
            break

    # Only check feature files that match the current "balanced_64" convention.
    # Legacy "aggregated" files use a different stem set and are intentionally
    # ignored here — they predate the balanced subsample contract.
    feature_files: List[Tuple[str, str]] = [
        ("qwen3_vl", feat_cfg["output_qwen3_vl"]),
        ("qwen3_5", feat_cfg["output_qwen3_5"]),
    ]
    # Also check resolution-variant siblings (e.g. _640x480.pt) of the current
    # balanced_64 files.
    for path_obj in Path(scene_root).glob("qwen*_features_balanced_64*.pt"):
        name = path_obj.name
        if not any(name == f for _, f in feature_files):
            kind = "qwen3_vl" if "qwen3_vl" in name else "qwen3_5"
            feature_files.append((kind, name))

    for kind, fname in feature_files:
        path = os.path.join(scene_root, fname)
        if not os.path.exists(path):
            continue  # missing features is not an error — user may not have generated them
        try:
            size = os.path.getsize(path)
        except OSError:
            size = 0
        if size == 0:
            issues.append(f"corrupt_features:{fname}:zero_byte")
            files_to_delete.append(path)
            continue
        try:
            data = torch.load(path, map_location="cpu", mmap=True, weights_only=False)
        except Exception as e:
            issues.append(f"corrupt_features:{fname}:{type(e).__name__}")
            files_to_delete.append(path)
            continue
        actual_keys = set(data.keys())
        if expected_feature_stems is not None:
            expected_set = set(expected_feature_stems)
            if actual_keys != expected_set:
                missing = len(expected_set - actual_keys)
                extra = len(actual_keys - expected_set)
                issues.append(
                    f"stale_features:{fname}:missing={missing},extra={extra}"
                )
                files_to_delete.append(path)
                continue

        # Spot-check shape on 3 random frames.
        sample = random.sample(list(actual_keys), min(3, len(actual_keys)))
        expected_layers = _expected_layer_count(fname)
        bad = False
        for k in sample:
            t = data[k]
            if t.dim() != 4 or t.shape[0] != expected_layers:
                bad = True
                break
        if bad:
            issues.append(f"corrupt_features:{fname}:bad_shape")
            files_to_delete.append(path)

    # ---- Build report line -----------------------------------------------
    if not issues:
        status = "OK"
        summary["verify_ok"] += 1
    else:
        status = "BAD"
        summary["verify_bad"] += 1
        for tag in issues:
            kind = tag.split(":", 1)[0]
            summary[f"verify_{kind}"] = summary.get(f"verify_{kind}", 0) + 1

    line = f"[{status}] {scene_id}: " + (", ".join(issues) if issues else "all checks passed")
    print(f"  {line}")
    report_lines.append(line)

    # ---- --delete repair --------------------------------------------------
    if args.delete and files_to_delete:
        # Deduplicate paths.
        files_to_delete = list(dict.fromkeys(files_to_delete))
        # Add dependent feature files for any deleted depth file.
        deleted_depth = [p for p in files_to_delete if "da3_geometry" in os.path.basename(p)]
        if deleted_depth:
            for kind, fname in feature_files:
                fpath = os.path.join(scene_root, fname)
                if os.path.exists(fpath):
                    files_to_delete.append(fpath)
        files_to_delete = list(dict.fromkeys(files_to_delete))

        for path in files_to_delete:
            try:
                if os.path.exists(path):
                    os.remove(path)
                    print(f"    deleted: {os.path.basename(path)}")
                    summary["verify_deleted"] += 1
            except OSError as e:
                print(f"    FAILED to delete {path}: {e}")


# ---------------------------------------------------------------------------
# Argument parsing + main
# ---------------------------------------------------------------------------


def parse_args():
    parser = argparse.ArgumentParser(
        description="Unified scene precompute pipeline (depth + features + verify).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--dataset", required=True, choices=sorted(DATASET_CONFIGS.keys()))

    # Phase flags (positive selection — any subset).
    parser.add_argument("--nonaligned", action="store_true",
                        help="Generate predicted-pose DA3 geometry (default _metric.pt).")
    parser.add_argument("--aligned", action="store_true",
                        help="Generate GT-pose-aligned geometry (_metric_aligned.pt). "
                             "Reuses depths/intrinsics from the nonaligned file if present; "
                             "pass --nonaligned --aligned to generate both from scratch.")
    parser.add_argument("--features", action="store_true",
                        help="Extract Qwen visual features.")
    parser.add_argument("--verify", action="store_true",
                        help="Run consistency checks (read-only by default).")

    # Variant flags.
    parser.add_argument("--no_metric", action="store_true",
                        help="Use non-metric DA3-Large instead of DA3NESTED-GIANT-LARGE-1.1. "
                             "Files are written WITHOUT the _metric suffix; the dataloader "
                             "does NOT read these — manual loader change required.")
    parser.add_argument("--feature_resolution", default="320x240",
                        help="Image resolution subdir/suffix for features phase. "
                             "Default 320x240; depth phases always use native resolution.")
    parser.add_argument("--model", default="Qwen/Qwen3-VL-8B-Instruct",
                        help="HF model id for the features phase.")

    # Scene selection.
    parser.add_argument("--scenes", nargs="+", default=None)
    parser.add_argument("--scene_start", type=int, default=None)
    parser.add_argument("--scene_end", type=int, default=None)
    parser.add_argument("--shuffle", action="store_true")
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--split", default=None,
                        help="ArkitScenes Training|Validation override.")

    # Verify cleanup.
    parser.add_argument("--delete", action="store_true",
                        help="In --verify mode, delete stale/corrupt files for regeneration.")

    args = parser.parse_args()

    # Default phases: nonaligned + features (the original two-script sequence).
    if not (args.nonaligned or args.aligned or args.features or args.verify):
        args.nonaligned = True
        args.features = True

    return args


def _validate_args(args, cfg):
    if args.no_metric and args.aligned:
        raise SystemExit(
            "--no_metric and --aligned are mutually exclusive (aligned needs the "
            "metric DA3 model for depth conditioning)."
        )
    if args.delete and not args.verify:
        print("WARNING: --delete has no effect without --verify; ignoring.")

    # VRAM pre-flight: warn if requesting depth + features together on a small GPU.
    needs_da3 = args.nonaligned  # aligned reuses nonaligned and doesn't load DA3
    needs_qwen = args.features
    if needs_da3 and needs_qwen and torch.cuda.is_available():
        try:
            total = torch.cuda.get_device_properties(0).total_memory
            if total < SMALL_GPU_BYTES:
                print(
                    f"\nWARNING: requesting depth + features in one invocation on a "
                    f"{total / 1024**3:.1f} GB GPU may OOM. Recommended split:\n"
                    f"  python scripts/precompute.py --dataset {args.dataset} --nonaligned [--aligned]\n"
                    f"  python scripts/precompute.py --dataset {args.dataset} --features\n"
                )
        except Exception:
            pass


def main():
    args = parse_args()
    cfg = DATASET_CONFIGS[args.dataset]
    _validate_args(args, cfg)

    _install_signal_handlers()
    torch.set_grad_enabled(False)

    print(f"Dataset: {args.dataset}")
    print(f"Phases: " + " ".join(
        flag for flag, on in [
            ("nonaligned", args.nonaligned),
            ("aligned", args.aligned),
            ("features", args.features),
            ("verify", args.verify),
        ] if on
    ))

    # ---- Lazy model loads (before the per-scene loop) ---------------------
    # Aligned reuses nonaligned's depths/intrinsics, so it does NOT need DA3
    # by itself. Only --nonaligned triggers DA3 loading.
    da3_model = None
    if args.nonaligned:
        da3_model = load_da3_model(metric=not args.no_metric)

    feature_model = None
    feature_processor = None
    feature_merge_size = None
    if args.features:
        feature_model, feature_processor = load_feature_model(args.model)
        feature_merge_size = feature_model.model.visual.spatial_merge_size

    # ---- Per-scene loop ---------------------------------------------------
    summary: Dict[str, int] = {
        "n_scenes": 0,
        "verify_ok": 0,
        "verify_bad": 0,
        "verify_deleted": 0,
        "nonaligned_processed": 0,
        "nonaligned_skipped": 0,
        "nonaligned_errors": 0,
        "aligned_processed": 0,
        "aligned_skipped": 0,
        "aligned_errors": 0,
        "features_processed": 0,
        "features_skipped": 0,
        "features_missing_geometry": 0,
        "features_corrupt_geometry": 0,
        "features_no_output": 0,
        "features_errors": 0,
    }
    verify_report: List[str] = []

    for scene_id, scene_root, color_files in _iter_scenes(cfg, args):
        summary["n_scenes"] += 1
        print(f"\n=== {scene_id} ===")
        try:
            if args.verify:
                verify_scene(cfg, args, scene_id, scene_root, color_files,
                             summary, verify_report)
            if args.nonaligned:
                nonaligned_scene(cfg, args, scene_id, scene_root, color_files,
                                 da3_model, summary)
            if args.aligned:
                aligned_scene(cfg, args, scene_id, scene_root, color_files,
                              da3_model, summary)
            if args.features:
                features_scene(cfg, args, scene_id, scene_root, color_files,
                               feature_model, feature_processor, feature_merge_size,
                               summary)
        except KeyboardInterrupt:
            raise
        except Exception as e:
            print(f"  ERROR processing {scene_id}: {e}")
            # Continue to the next scene; per-phase errors are already counted.

    # ---- Cleanup models ---------------------------------------------------
    del da3_model, feature_model, feature_processor
    cleanup_gpu()

    # ---- Final summary ----------------------------------------------------
    print("\n" + "=" * 60)
    print(f"Precompute summary ({args.dataset})")
    print("=" * 60)
    print(f"  scenes seen:                 {summary['n_scenes']}")
    if args.verify:
        print(f"  verify ok:                   {summary['verify_ok']}")
        print(f"  verify bad:                  {summary['verify_bad']}")
        if args.delete:
            print(f"  verify deleted (files):      {summary['verify_deleted']}")
        # Also show breakdown by issue kind.
        issue_counts = {k: v for k, v in summary.items()
                        if k.startswith("verify_") and k not in
                        ("verify_ok", "verify_bad", "verify_deleted")}
        for k, v in sorted(issue_counts.items()):
            print(f"    {k:<28} {v}")
    if args.nonaligned:
        print(f"  nonaligned processed:        {summary['nonaligned_processed']}")
        print(f"  nonaligned skipped:          {summary['nonaligned_skipped']}")
        print(f"  nonaligned errors:           {summary['nonaligned_errors']}")
    if args.aligned:
        print(f"  aligned processed:           {summary['aligned_processed']}")
        print(f"  aligned skipped:             {summary['aligned_skipped']}")
        print(f"  aligned errors:              {summary['aligned_errors']}")
    if args.features:
        print(f"  features processed:          {summary['features_processed']}")
        print(f"  features skipped:            {summary['features_skipped']}")
        print(f"  features missing geometry:   {summary['features_missing_geometry']}")
        print(f"  features corrupt geometry:   {summary['features_corrupt_geometry']}")
        print(f"  features no output:          {summary['features_no_output']}")
        print(f"  features errors:             {summary['features_errors']}")
    print("=" * 60)


if __name__ == "__main__":
    main()
